apiVersion: v1
kind: Pod
metadata:
  name: active-mq-queue
  labels:
    app: queue
spec:
  containers:
    - name: queue
      image: richardchesterwood/k8s-fleetman-queue:release1


#DockerImageref-- https://www.udemy.com/course/kubernetes-microservices/